workflows:
  android-build:
    name: Build Chronus APK
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        PACKAGE_NAME: "org.telegram.messenger"

    scripts:
      - name: Checkout Submodules Deeply
        script: | 
          git submodule deinit -f . || true
          git submodule update --init --recursive --force

      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Grant execute permissions for gradlew
        script: | 
          chmod +x gradlew

      - name: Build Android APK
        script: | 
          ./gradlew assembleDebug --no-daemon --stacktrace

    artifacts:
      - app/build/outputs/apk/**/*.apk
